version: 2.1
orbs:
  node: circleci/node@4.1.0
  cypress: cypress-io/cypress@1.26.0
jobs:
  run-unit-tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test -u --maxWorkers=1 --maxConcurrency=1
          name: Run Jest tests
workflows:
  node-tests:
    jobs:
      - run-unit-tests
      - cypress/run:
          name: start-dev-and-test
          yarn: true
          start: yarn dev
          wait-on: 'http://localhost:4000'
