const timezones = {
  Australia: {
    Sydney: 'Australia/Sydney',
    Eucla: 'Australia/Eucla',
    'Lord Howe': 'Australia/Lord_Howe',
    Darwin: 'Australia/Darwin',
    Brisbane: 'Australia/Brisbane',
    Adelaide: 'Australia/Adelaide',
    Hobart: 'Australia/Hobart',
    Melbourne: 'Australia/Melbourne',
    Perth: 'Australia/Perth'
  },
  Asia: {
    'Jordan Time': 'Asia/Amman',
    'Baghdad, East Africa Time': 'Asia/Baghdad',
    'Dubai Time': 'Asia/Dubai',
    'Hong Kong': 'Asia/Hong_Kong',
    Tehran: 'Asia/Tehran',
    Jerusalem: 'Asia/Jerusalem',
    Tokyo: 'Asia/Tokyo',
    Shanghai: 'Asia/Shanghai',
    Taipei: 'Asia/Taipei',
    Seoul: 'Asia/Seoul',
    Singapore: 'Asia/Singapore',
    Baku: 'Asia/Baku',
    Dhaka: 'Asia/Dhaka',
    Gaza: 'Asia/Gaza',
    Irkutsk: 'Asia/Irkutsk',
    Omsk: 'Asia/Omsk',
    Rangoon: 'Asia/Rangoon',
    Vladivostok: 'Asia/Vladivostok',
    Yakutsk: 'Asia/Yakutsk',
    Yerevan: 'Asia/Yerevan',
    'Pacific/Majuro': 'Asia/Kamchatka'
  },
  Europe: {
    'Central European Time': 'Europe/Berlin',
    'Eastern European Time': 'Europe/Helsinki',
    Helsinki: 'Europe/Helsinki',
    Berlin: 'Europe/Berlin',
    Paris: 'Europe/Paris',
    Sofia: 'Europe/Sofia',
    Dublin: 'Europe/Dublin',
    London: 'Europe/London',
    Warsaw: 'Europe/Warsaw',
    Istanbul: 'Europe/Istanbul',
    Lisbon: 'Europe/Lisbon',
    Moscow: 'Europe/Moscow'
  },
  Atlantic: {
    Reykjavik: 'Atlantic/Reykjavik',
    'Azores Time': 'Atlantic/Azores',
    'Cape Verde Time': 'Atlantic/Cape_Verde',
    'Atlantic Time': 'America/Goose_Bay',
    'Atlantic Standard Time': 'America/Santo_Domingo'
  },
  Pacific: {
    Apia: 'Pacific/Apia',
    Auckland: 'Pacific/Auckland',
    Chatham: 'Pacific/Chatham',
    Easter: 'Pacific/Easter',
    Fiji: 'Pacific/Fiji',
    Gambier: 'Pacific/Gambier',
    Kiritimati: 'Pacific/Kiritimati',
    Majuro: 'Pacific/Majuro',
    Marquesas: 'Pacific/Marquesas',
    Norfolk: 'Pacific/Norfolk',
    Noumea: 'Pacific/Noumea',
    Pitcairn: 'Pacific/Pitcairn',
    Tarawa: 'Pacific/Tarawa',
    Tongatapu: 'Pacific/Tongatapu',
    Honolulu: 'Pacific/Honolulu',
    Kwajalein: 'Pacific/Kwajalein',
    'Pago Pago': 'Pacific/Pago_Pago'
  },
  'US/Canada': {
    'Pacific Time': 'America/Los_Angeles',
    'Mountain Time': 'America/Denver',
    'Central Time': 'America/Chicago',
    'Eastern Time': 'America/New_York',
    'Alaska Time': 'America/Anchorage',
    'Arizona Time': 'America/Phoenix',
    'Newfoundland Time': 'America/St_Johns',
    'Hawaii Time': 'Pacific/Honolulu'
  },
  America: {
    'Rio Branco': 'America/Rio_Branco',
    Noronha: 'America/Noronha',
    'Sao Paulo': 'America/Sao_Paulo',
    Manaus: 'America/Manaus',
    Halifax: 'America/Halifax',
    Winnipeg: 'America/Winnipeg',
    Toronto: 'America/Toronto',
    Edmonton: 'America/Edmonton',
    Santiago: 'America/Santiago',
    'St Johns': 'America/St_Johns',
    Vancouver: 'America/Vancouver',
    Regina: 'America/Regina',
    Whitehorse: 'America/Whitehorse',
    Cancun: 'America/Cancun',
    'New York': 'America/New_York',
    Jamaica: 'America/Jamaica',
    Tijuana: 'America/Tijuana',
    Mazatlan: 'America/Mazatlan',
    'Mexico City': 'America/Mexico_City',
    Phoenix: 'America/Phoenix',
    Denver: 'America/Denver',
    Anchorage: 'America/Anchorage',
    Adak: 'America/Adak',
    Chicago: 'America/Chicago',
    Indianapolis: 'America/Indiana/Indianapolis',
    Knox: 'America/Indiana/Knox',
    Detroit: 'America/Detroit',
    'Los Angeles': 'America/Los_Angeles',
    'Bogota, Jamaica, Lima Time': 'America/Bogota',
    'Caracas Time': 'America/Caracas',
    Havana: 'America/Havana',
    'Santa Isabel': 'America/Santa_Isabel',
    'Brasilia Time': 'America/Sao_Paulo'
  },
  Africa: {
    Cairo: 'Africa/Cairo',
    'Central Africa Time': 'Africa/Johannesburg',
    'West Africa Time': 'Africa/Lagos',
    Windhoek: 'Africa/Windhoek',
    Tripoli: 'Africa/Tripoli'
  },
  UTC: {
    'UTC Time': 'UTC'
  }
};

export default timezones;
