const timezones = {
  Australia: {
    Perth: 'Australia/Perth',
    Eucla: 'Australia/Eucla',
    Darwin: 'Australia/Darwin',
    Brisbane: 'Australia/Brisbane',
    Lindeman: 'Australia/Lindeman',
    Adelaide: 'Australia/Adelaide',
    'Broken Hill': 'Australia/Broken_Hill',
    Sydney: 'Australia/Sydney',
    Hobart: 'Australia/Hobart',
    Melbourne: 'Australia/Melbourne',
    'Lord Howe': 'Australia/Lord_Howe'
  },
  Asia: {
    'Jordan Time': 'Asia/Amman',
    'East Africa Time': 'Asia/Baghdad',
    'Dubai Time': 'Asia/Dubai',
    Amman: 'Asia/Amman',
    Beirut: 'Asia/Beirut',
    Damascus: 'Asia/Damascus',
    Gaza: 'Asia/Gaza',
    Nicosia: 'Asia/Nicosia',
    Famagusta: 'Asia/Famagusta',
    Jerusalem: 'Asia/Jerusalem',
    Aden: 'Asia/Aden',
    Baghdad: 'Asia/Baghdad',
    Bahrain: 'Asia/Bahrain',
    Kuwait: 'Asia/Kuwait',
    Qatar: 'Asia/Qatar',
    Riyadh: 'Asia/Riyadh',
    Tehran: 'Asia/Tehran',
    Yerevan: 'Asia/Yerevan',
    Baku: 'Asia/Baku',
    Tbilisi: 'Asia/Tbilisi',
    Dubai: 'Asia/Dubai',
    Muscat: 'Asia/Muscat',
    Kabul: 'Asia/Kabul',
    Karachi: 'Asia/Karachi',
    Dushanbe: 'Asia/Dushanbe',
    Ashgabat: 'Asia/Ashgabat',
    Samarkand: 'Asia/Samarkand',
    Tashkent: 'Asia/Tashkent',
    Qyzylorda: 'Asia/Qyzylorda',
    Aqtau: 'Asia/Aqtau',
    Aqtobe: 'Asia/Aqtobe',
    Atyrau: 'Asia/Atyrau',
    Oral: 'Asia/Oral',
    Yekaterinburg: 'Asia/Yekaterinburg',
    Colombo: 'Asia/Colombo',
    Kolkata: 'Asia/Kolkata',
    Kathmandu: 'Asia/Kathmandu',
    Dhaka: 'Asia/Dhaka',
    Thimphu: 'Asia/Thimphu',
    Almaty: 'Asia/Almaty',
    Qostanay: 'Asia/Qostanay',
    Urumqi: 'Asia/Urumqi',
    Bishkek: 'Asia/Bishkek',
    Omsk: 'Asia/Omsk',
    Yangon: 'Asia/Yangon',
    Hovd: 'Asia/Hovd',
    Bangkok: 'Asia/Bangkok',
    'Ho Chi Minh': 'Asia/Ho_Chi_Minh',
    'Phnom Penh': 'Asia/Phnom_Penh',
    Vientiane: 'Asia/Vientiane',
    Novosibirsk: 'Asia/Novosibirsk',
    Barnaul: 'Asia/Barnaul',
    Krasnoyarsk: 'Asia/Krasnoyarsk',
    Novokuznetsk: 'Asia/Novokuznetsk',
    Tomsk: 'Asia/Tomsk',
    Jakarta: 'Asia/Jakarta',
    Brunei: 'Asia/Brunei',
    Makassar: 'Asia/Makassar',
    Macau: 'Asia/Macau',
    Shanghai: 'Asia/Shanghai',
    'Hong Kong': 'Asia/Hong_Kong',
    Irkutsk: 'Asia/Irkutsk',
    'Kuala Lumpur': 'Asia/Kuala_Lumpur',
    Kuching: 'Asia/Kuching',
    Manila: 'Asia/Manila',
    Singapore: 'Asia/Singapore',
    Taipei: 'Asia/Taipei',
    Ulaanbaatar: 'Asia/Ulaanbaatar',
    Choibalsan: 'Asia/Choibalsan',
    Dili: 'Asia/Dili',
    Jayapura: 'Asia/Jayapura',
    Tokyo: 'Asia/Tokyo',
    Pyongyang: 'Asia/Pyongyang',
    Seoul: 'Asia/Seoul',
    Chita: 'Asia/Chita',
    Khandyga: 'Asia/Khandyga',
    Yakutsk: 'Asia/Yakutsk',
    Vladivostok: 'Asia/Vladivostok',
    Nera: 'Asia/Ust-Nera',
    Magadan: 'Asia/Magadan',
    Sakhalin: 'Asia/Sakhalin',
    Srednekolymsk: 'Asia/Srednekolymsk',
    Anadyr: 'Asia/Anadyr',
    Kamchatka: 'Asia/Kamchatka'
  },
  Europe: {
    'Central European Time': 'Europe/Berlin',
    'Eastern European Time': 'Europe/Helsinki',
    Dublin: 'Europe/Dublin',
    Guernsey: 'Europe/Guernsey',
    'Isle of Man': 'Europe/Isle_of_Man',
    Jersey: 'Europe/Jersey',
    London: 'Europe/London',
    Lisbon: 'Europe/Lisbon',
    Amsterdam: 'Europe/Amsterdam',
    Andorra: 'Europe/Andorra',
    Belgrade: 'Europe/Belgrade',
    Berlin: 'Europe/Berlin',
    Busingen: 'Europe/Busingen',
    Bratislava: 'Europe/Bratislava',
    Brussels: 'Europe/Brussels',
    Budapest: 'Europe/Budapest',
    Copenhagen: 'Europe/Copenhagen',
    Gibraltar: 'Europe/Gibraltar',
    Ljubljana: 'Europe/Ljubljana',
    Luxembourg: 'Europe/Luxembourg',
    Madrid: 'Europe/Madrid',
    Malta: 'Europe/Malta',
    Monaco: 'Europe/Monaco',
    Oslo: 'Europe/Oslo',
    Paris: 'Europe/Paris',
    Podgorica: 'Europe/Podgorica',
    Prague: 'Europe/Prague',
    Rome: 'Europe/Rome',
    'San Marino': 'Europe/San_Marino',
    Sarajevo: 'Europe/Sarajevo',
    Skopje: 'Europe/Skopje',
    Stockholm: 'Europe/Stockholm',
    Tirane: 'Europe/Tirane',
    Vaduz: 'Europe/Vaduz',
    Vatican: 'Europe/Vatican',
    Vienna: 'Europe/Vienna',
    Warsaw: 'Europe/Warsaw',
    Zagreb: 'Europe/Zagreb',
    Zurich: 'Europe/Zurich',
    Athens: 'Europe/Athens',
    Bucharest: 'Europe/Bucharest',
    Chisinau: 'Europe/Chisinau',
    Helsinki: 'Europe/Helsinki',
    Kaliningrad: 'Europe/Kaliningrad',
    Kiev: 'Europe/Kiev',
    Uzhgorod: 'Europe/Uzhgorod',
    Mariehamn: 'Europe/Mariehamn',
    Riga: 'Europe/Riga',
    Sofia: 'Europe/Sofia',
    Tallinn: 'Europe/Tallinn',
    Vilnius: 'Europe/Vilnius',
    Istanbul: 'Europe/Istanbul',
    Minsk: 'Europe/Minsk',
    'Moscow Time': 'Europe/Moscow',
    Samara: 'Europe/Samara',
    Volgograd: 'Europe/Volgograd'
  },
  Atlantic: {
    'Atlantic Time': 'America/Goose_Bay',
    'Atlantic Standard Time': 'America/Santo_Domingo',
    Stanley: 'Atlantic/Stanley',
    'South Georgia': 'Atlantic/South_Georgia',
    Azores: 'Atlantic/Azores',
    'Cape Verde': 'Atlantic/Cape_Verde',
    Reykjavik: 'Atlantic/Reykjavik',
    'St Helena': 'Atlantic/St_Helena',
    Canary: 'Atlantic/Canary',
    Faroe: 'Atlantic/Faroe',
    Madeira: 'Atlantic/Madeira'
  },
  Antarctica: {
    Troll: 'Antarctica/Troll',
    Syowa: 'Antarctica/Syowa',
    Mawson: 'Antarctica/Mawson',
    Vostok: 'Antarctica/Vostok',
    Davis: 'Antarctica/Davis',
    Casey: 'Antarctica/Casey',
    Macquarie: 'Antarctica/Macquarie',
    DumontDUrville: 'Antarctica/DumontDUrville'
  },
  Arctic: {
    Longyearbyen: 'Arctic/Longyearbyen',
    Danmarkshavn: 'America/Danmarkshavn',
    Scoresbysund: 'America/Scoresbysund'
  },
  Pacific: {
    Niue: 'Pacific/Niue',
    Midway: 'Pacific/Midway',
    'Pago Pago': 'Pacific/Pago_Pago',
    Rarotonga: 'Pacific/Rarotonga',
    Honolulu: 'Pacific/Honolulu',
    Tahiti: 'Pacific/Tahiti',
    Marquesas: 'Pacific/Marquesas',
    Gambier: 'Pacific/Gambier',
    Pitcairn: 'Pacific/Pitcairn',
    Galapagos: 'Pacific/Galapagos',
    Easter: 'Pacific/Easter',
    Palau: 'Pacific/Palau',
    Guam: 'Pacific/Guam',
    Saipan: 'Pacific/Saipan',
    Chuuk: 'Pacific/Chuuk',
    'Port Moresby': 'Pacific/Port_Moresby',
    Bougainville: 'Pacific/Bougainville',
    'Kosrae, Pohnpei': 'Pacific/Kosrae',
    Noumea: 'Pacific/Noumea',
    Guadalcanal: 'Pacific/Guadalcanal',
    Efate: 'Pacific/Efate',
    Tarawa: 'Pacific/Tarawa',
    'Majuro, Kwajalein': 'Pacific/Kwajalein',
    Nauru: 'Pacific/Nauru',
    Norfolk: 'Pacific/Norfolk',
    Funafuti: 'Pacific/Funafuti',
    Wake: 'Pacific/Wake',
    Wallis: 'Pacific/Wallis',
    Fiji: 'Pacific/Fiji',
    Auckland: 'Pacific/Auckland',
    Enderbury: 'Pacific/Enderbury',
    Fakaofo: 'Pacific/Fakaofo',
    Tongatapu: 'Pacific/Tongatapu',
    Chatham: 'Pacific/Chatham',
    Apia: 'Pacific/Apia',
    Kiritimati: 'Pacific/Kiritimati'
  },
  'US/Canada': {
    'Pacific Time': 'America/Los_Angeles',
    'Mountain Time': 'America/Denver',
    'Central Time': 'America/Chicago',
    'Eastern Time': 'America/New_York',
    'Alaska Time': 'America/Anchorage',
    'Arizona Time': 'America/Phoenix',
    'Newfoundland Time': 'America/St_Johns',
    'Hawaii Time': 'Pacific/Honolulu',
    Adak: 'America/Adak',
    Anchorage: 'America/Anchorage',
    Juneau: 'America/Juneau',
    Metlakatla: 'America/Metlakatla',
    Nome: 'America/Nome',
    Sitka: 'America/Sitka',
    Yakutat: 'America/Yakutat',
    'Los Angeles': 'America/Los_Angeles',
    Vancouver: 'America/Vancouver',
    Whitehorse: 'America/Whitehorse',
    Dawson: 'America/Dawson',
    Creston: 'America/Creston',
    'Dawson Creek': 'America/Dawson_Creek',
    'Fort Nelson': 'America/Fort_Nelson',
    Denver: 'America/Denver',
    Boise: 'America/Boise',
    Edmonton: 'America/Edmonton',
    'Cambridge Bay': 'America/Cambridge_Bay',
    Yellowknife: 'America/Yellowknife',
    Phoenix: 'America/Phoenix',
    Chicago: 'America/Chicago',
    'Knox, Indiana': 'America/Indiana/Knox',
    'Tell City, Indiana': 'America/Indiana/Tell_City',
    'Beulah, North Dakota': 'America/North_Dakota/Beulah',
    'Center, North Dakota': 'America/North_Dakota/Center',
    'New Salem, North Dakota': 'America/North_Dakota/New_Salem',
    Menominee: 'America/Menominee',
    Regina: 'America/Regina',
    Winnipeg: 'America/Winnipeg',
    'Rainy River': 'America/Rainy_River',
    'Rankin Inlet': 'America/Rankin_Inlet',
    Resolute: 'America/Resolute',
    Atikokan: 'America/Atikokan',
    'New York': 'America/New_York',
    'Indianapolis, Indiana': 'America/Indiana/Indianapolis',
    'Marengo, Indiana': 'America/Indiana/Marengo',
    'Petersburg, Indiana': 'America/Indiana/Petersburg',
    'Vevay, Indiana': 'America/Indiana/Vevay',
    'Vincennes, Indiana': 'America/Indiana/Vincennes',
    'Winamac, Indiana': 'America/Indiana/Winamac',
    'Louisville, Kentucky': 'America/Kentucky/Louisville',
    'Monticello, Kentucky': 'America/Kentucky/Monticello',
    Toronto: 'America/Toronto',
    Iqaluit: 'America/Iqaluit',
    Nipigon: 'America/Nipigon',
    Pangnirtung: 'America/Pangnirtung',
    'Thunder Bay': 'America/Thunder_Bay',
    Halifax: 'America/Halifax',
    'Glace Bay': 'America/Glace_Bay',
    'Goose Bay': 'America/Goose_Bay',
    Moncton: 'America/Moncton'
  },
  America: {
    'Brasilia Time': 'America/Sao_Paulo',
    Tijuana: 'America/Tijuana',
    Chihuahua: 'America/Chihuahua',
    Mazatlan: 'America/Mazatlan',
    Ojinaga: 'America/Ojinaga',
    Hermosillo: 'America/Hermosillo',
    Inuvik: 'America/Inuvik',
    Belize: 'America/Belize',
    'Costa Rica': 'America/Costa_Rica',
    'El Salvador': 'America/El_Salvador',
    Guatemala: 'America/Guatemala',
    Managua: 'America/Managua',
    'Mexico City': 'America/Mexico_City',
    'Bahia Banderas': 'America/Bahia_Banderas',
    Matamoros: 'America/Matamoros',
    Merida: 'America/Merida',
    Monterrey: 'America/Monterrey',
    'Swift Current': 'America/Swift_Current',
    Tegucigalpa: 'America/Tegucigalpa',
    'Rio Branco': 'America/Rio_Branco',
    Eirunepe: 'America/Eirunepe',
    Bogota: 'America/Bogota',
    Havana: 'America/Havana',
    Cancun: 'America/Cancun',
    Cayman: 'America/Cayman',
    'Grand Turk': 'America/Grand_Turk',
    Jamaica: 'America/Jamaica',
    Nassau: 'America/Nassau',
    Panama: 'America/Panama',
    Prince: 'America/Port-au-Prince',
    Guayaquil: 'America/Guayaquil',
    Lima: 'America/Lima',
    Manaus: 'America/Manaus',
    'Boa Vista': 'America/Boa_Vista',
    'Campo Grande': 'America/Campo_Grande',
    Cuiaba: 'America/Cuiaba',
    'Porto Velho': 'America/Porto_Velho',
    Anguilla: 'America/Anguilla',
    Antigua: 'America/Antigua',
    Aruba: 'America/Aruba',
    Barbados: 'America/Barbados',
    Bermuda: 'Atlantic/Bermuda',
    Sablon: 'America/Blanc-Sablon',
    Curacao: 'America/Curacao',
    Dominica: 'America/Dominica',
    Grenada: 'America/Grenada',
    Guadeloupe: 'America/Guadeloupe',
    Kralendijk: 'America/Kralendijk',
    'Lower Princes': 'America/Lower_Princes',
    Marigot: 'America/Marigot',
    Martinique: 'America/Martinique',
    Montserrat: 'America/Montserrat',
    'Port of Spain': 'America/Port_of_Spain',
    'Puerto Rico': 'America/Puerto_Rico',
    'Santo Domingo': 'America/Santo_Domingo',
    'St Barthelemy': 'America/St_Barthelemy',
    'St Kitts': 'America/St_Kitts',
    'St Lucia': 'America/St_Lucia',
    'St Thomas': 'America/St_Thomas',
    'St Vincent': 'America/St_Vincent',
    Thule: 'America/Thule',
    Tortola: 'America/Tortola',
    'La Paz': 'America/La_Paz',
    Guyana: 'America/Guyana',
    Caracas: 'America/Caracas',
    'St Johns': 'America/St_Johns',
    'Buenos Aires': 'America/Argentina/Buenos_Aires',
    Catamarca: 'America/Argentina/Catamarca',
    Cordoba: 'America/Argentina/Cordoba',
    Jujuy: 'America/Argentina/Jujuy',
    'La Rioja': 'America/Argentina/La_Rioja',
    Mendoza: 'America/Argentina/Mendoza',
    'Rio Gallegos': 'America/Argentina/Rio_Gallegos',
    Tucuman: 'America/Argentina/Tucuman',
    'San Luis': 'America/Argentina/San_Luis',
    'San Juan': 'America/Argentina/San_Juan',
    Ushuaia: 'America/Argentina/Ushuaia',
    'Sao Paulo': 'America/Sao_Paulo',
    Araguaina: 'America/Araguaina',
    Bahia: 'America/Bahia',
    Belem: 'America/Belem',
    Fortaleza: 'America/Fortaleza',
    Maceio: 'America/Maceio',
    Recife: 'America/Recife',
    Santarem: 'America/Santarem',
    Santiago: 'America/Santiago',
    Cayenne: 'America/Cayenne',
    Palmer: 'Antarctica/Palmer',
    Rothera: 'Antarctica/Rothera',
    'Punta Arenas': 'America/Punta_Arenas',
    Asuncion: 'America/Asuncion',
    Miquelon: 'America/Miquelon',
    Paramaribo: 'America/Paramaribo',
    Montevideo: 'America/Montevideo',
    Godthab: 'America/Godthab',
    Noronha: 'America/Noronha'
  },
  Africa: {
    'Central Africa Time': 'Africa/Johannesburg',
    'West Africa Time': 'Africa/Lagos',
    Abidjan: 'Africa/Abidjan',
    Accra: 'Africa/Accra',
    Bamako: 'Africa/Bamako',
    Banjul: 'Africa/Banjul',
    Bissau: 'Africa/Bissau',
    Conakry: 'Africa/Conakry',
    Dakar: 'Africa/Dakar',
    Freetown: 'Africa/Freetown',
    Lome: 'Africa/Lome',
    Monrovia: 'Africa/Monrovia',
    Nouakchott: 'Africa/Nouakchott',
    Ouagadougou: 'Africa/Ouagadougou',
    'Sao Tome': 'Africa/Sao_Tome',
    Algiers: 'Africa/Algiers',
    Tunis: 'Africa/Tunis',
    Casablanca: 'Africa/Casablanca',
    'El Aaiun': 'Africa/El_Aaiun',
    Bangui: 'Africa/Bangui',
    Brazzaville: 'Africa/Brazzaville',
    Douala: 'Africa/Douala',
    Kinshasa: 'Africa/Kinshasa',
    Lagos: 'Africa/Lagos',
    Libreville: 'Africa/Libreville',
    Luanda: 'Africa/Luanda',
    Malabo: 'Africa/Malabo',
    Ndjamena: 'Africa/Ndjamena',
    Niamey: 'Africa/Niamey',
    'Porto-Novo': 'Africa/Porto-Novo',
    Blantyre: 'Africa/Blantyre',
    Bujumbura: 'Africa/Bujumbura',
    Gaborone: 'Africa/Gaborone',
    Harare: 'Africa/Harare',
    Khartoum: 'Africa/Khartoum',
    Kigali: 'Africa/Kigali',
    Lubumbashi: 'Africa/Lubumbashi',
    Lusaka: 'Africa/Lusaka',
    Maputo: 'Africa/Maputo',
    Windhoek: 'Africa/Windhoek',
    Cairo: 'Africa/Cairo',
    Tripoli: 'Africa/Tripoli',
    Johannesburg: 'Africa/Johannesburg',
    Maseru: 'Africa/Maseru',
    Mbabane: 'Africa/Mbabane',
    'Addis Ababa': 'Africa/Addis_Ababa',
    Ceuta: 'Africa/Ceuta',
    Asmara: 'Africa/Asmara',
    'Dar es Salaam': 'Africa/Dar_es_Salaam',
    Djibouti: 'Africa/Djibouti',
    Juba: 'Africa/Juba',
    Kampala: 'Africa/Kampala',
    Mogadishu: 'Africa/Mogadishu',
    Nairobi: 'Africa/Nairobi'
  },
  Indian: {
    Antananarivo: 'Indian/Antananarivo',
    Comoro: 'Indian/Comoro',
    Mayotte: 'Indian/Mayotte',
    Mauritius: 'Indian/Mauritius',
    Reunion: 'Indian/Reunion',
    Mahe: 'Indian/Mahe',
    Kerguelen: 'Indian/Kerguelen',
    Maldives: 'Indian/Maldives',
    Chagos: 'Indian/Chagos',
    Cocos: 'Indian/Cocos',
    Christmas: 'Indian/Christmas'
  },
  UTC: {
    'UTC Time': 'UTC'
  }
};

export default timezones;
